CREATE TABLE "JHCMS"."T_ARTICLE" 
   (	"ARTICLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(500) NOT NULL ENABLE, 
	"SHOW_TITLE" VARCHAR2(500), 
	"BRIEF" VARCHAR2(4000), 
	"URL" VARCHAR2(255), 
	"KEYWORD" VARCHAR2(255), 
	"REL_KEYWORD" VARCHAR2(50), 
	"AUTHOR" VARCHAR2(255), 
	"SOURCE" VARCHAR2(500), 
	"IS_PICTURE" NUMBER(10,0), 
	"PICTURE_URL" VARCHAR2(255), 
	"IS_HOT" NUMBER(10,0) DEFAULT 0, 
	"IS_NEW" NUMBER(10,0) DEFAULT 0, 
	"IS_HEAD" NUMBER(10,0) DEFAULT 0, 
	"PUBLISH_BY" VARCHAR2(50), 
	"PUBLISH_DATE" VARCHAR2(30), 
	"CATALOG_ID" NUMBER(10,0), 
	"SITENO" VARCHAR2(50), 
	"TYPE" NUMBER(10,0) NOT NULL ENABLE, 
	"LINK_URL" VARCHAR2(200), 
	"STATE" NUMBER(10,0), 
	"ORDERLINE" NUMBER(10,0), 
	"REVIEW" NUMBER(10,0), 
	"COMMENT_TIMES" NUMBER(10,0), 
	"HITS" NUMBER(10,0), 
	"IN_FLAG" NUMBER(10,0), 
	"USER_RIGHT" VARCHAR2(2000), 
	"ROLE_RIGHT" VARCHAR2(2000), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(30), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(30), 
	"REL_SECU" VARCHAR2(1000), 
	"BEGIN_TIME" VARCHAR2(20), 
	"END_TIME" VARCHAR2(20), 
	"IMPORTANT_LEVEL" VARCHAR2(20), 
	"GUID" VARCHAR2(100), 
	"NETWORK_NAME" VARCHAR2(30), 
	"GPDM" VARCHAR2(100), 
	"DATA_TYPE" VARCHAR2(10), 
	"CATALOG_NO" VARCHAR2(255), 
	"SOURCE_UNIQUE" VARCHAR2(30), 
	"FOREWORD" VARCHAR2(1000), 
	"REL_SECU_NAME" VARCHAR2(20), 
	"LASTMODIFYTIME" VARCHAR2(30), 
	"INDUSTRY_TYPE" VARCHAR2(30), 
	"COLUMN_LEVEL" NUMBER(10,0), 
	"PUBLISH_TIMING" VARCHAR2(30), 
	 CONSTRAINT "PK_T_ARTICLE" PRIMARY KEY ("ARTICLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ARTICLE_AUDIT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ARTICLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	 CONSTRAINT "PK_T_ARTICLE_AUDIT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ARTICLE_AUTHOR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(30), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFY_DATE" VARCHAR2(20), 
	"SITENO" VARCHAR2(20), 
	"CREATEBY" VARCHAR2(20), 
	 CONSTRAINT "PK_T_ARTICLE_AUTHOR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ARTICLE_CONTENT" 
   (	"ARTICLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CONTENT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
CREATE TABLE "JHCMS"."T_ARTICLE_EXTEND_FIELD" 
   (	"ARTICLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EXT_FIELD0" VARCHAR2(1000), 
	"EXT_FIELD1" VARCHAR2(1000), 
	"EXT_FIELD2" VARCHAR2(1000), 
	"EXT_FIELD3" VARCHAR2(1000), 
	"EXT_FIELD4" VARCHAR2(1000), 
	"EXT_FIELD5" VARCHAR2(1000), 
	"EXT_FIELD6" VARCHAR2(1000), 
	"EXT_FIELD7" VARCHAR2(1000), 
	"EXT_FIELD8" VARCHAR2(1000), 
	"EXT_FIELD9" VARCHAR2(1000), 
	"EXT_FIELD10" VARCHAR2(1000), 
	"EXT_FIELD11" VARCHAR2(1000), 
	"EXT_FIELD12" VARCHAR2(1000), 
	"EXT_FIELD13" VARCHAR2(1000), 
	"EXT_FIELD14" VARCHAR2(1000), 
	"EXT_FIELD15" VARCHAR2(1000), 
	"EXT_FIELD16" VARCHAR2(1000), 
	"EXT_FIELD17" VARCHAR2(1000), 
	"EXT_FIELD18" VARCHAR2(1000), 
	"EXT_FIELD19" VARCHAR2(1000), 
	"EXT_FIELD20" VARCHAR2(1000), 
	"EXT_FIELD21" VARCHAR2(1000), 
	"EXT_FIELD22" VARCHAR2(1000), 
	"EXT_FIELD23" VARCHAR2(1000), 
	"EXT_FIELD24" VARCHAR2(1000), 
	"EXT_FIELD25" VARCHAR2(1000), 
	"EXT_FIELD26" VARCHAR2(1000), 
	"EXT_FIELD27" VARCHAR2(1000), 
	"EXT_FIELD28" VARCHAR2(1000), 
	"EXT_FIELD29" VARCHAR2(1000), 
	"EXT_FIELD30" VARCHAR2(1000), 
	"EXT_FIELD31" VARCHAR2(1000), 
	"EXT_FIELD32" VARCHAR2(1000), 
	"EXT_FIELD33" VARCHAR2(1000), 
	"EXT_FIELD34" VARCHAR2(1000), 
	"EXT_FIELD35" VARCHAR2(1000), 
	"EXT_FIELD36" VARCHAR2(1000), 
	"EXT_FIELD37" VARCHAR2(1000), 
	"EXT_FIELD38" VARCHAR2(1000), 
	"EXT_FIELD39" VARCHAR2(1000), 
	"EXT_FIELD40" VARCHAR2(1000), 
	"EXT_FIELD41" VARCHAR2(1000), 
	"EXT_FIELD42" VARCHAR2(1000), 
	"EXT_FIELD43" VARCHAR2(1000), 
	"EXT_FIELD44" VARCHAR2(1000), 
	"EXT_FIELD45" VARCHAR2(1000), 
	"EXT_FIELD46" VARCHAR2(1000), 
	"EXT_FIELD47" VARCHAR2(1000), 
	"EXT_FIELD48" VARCHAR2(1000), 
	"EXT_FIELD49" VARCHAR2(1000), 
	"EXT_FIELD50" VARCHAR2(1000), 
	 CONSTRAINT "PK_EXTEND_FIELD_ARTICLE_ID" PRIMARY KEY ("ARTICLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ARTICLE_EXTEND_INFO" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CATALOG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"RECURSION" NUMBER(10,0), 
	"INPUT_TYPE" NUMBER(10,0), 
	"NAME" VARCHAR2(30), 
	"CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"ISMANDATORY" NUMBER(10,0), 
	"DEFAULT_VALUE" VARCHAR2(400), 
	"CREATE_BY" VARCHAR2(30), 
	"CREATE_DATE" VARCHAR2(30), 
	"MODIFY_BY" VARCHAR2(30), 
	"MODIFY_DATE" VARCHAR2(30), 
	"MAX_NUM" NUMBER(10,0), 
	"WIDTH" NUMBER(10,0), 
	"HEIGHT" NUMBER(10,0), 
	"EXTEND_CONTENT" VARCHAR2(1000), 
	"ORDERLINE" NUMBER(10,0), 
	"ALIAS" VARCHAR2(30), 
	 CONSTRAINT "PK_FIELD_EXTEND_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE, 
	 CONSTRAINT "PK_FIELD_EXTEND_UNITE_CODE" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ARTICLE_KEYWORD" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50), 
	"URL" VARCHAR2(255), 
	"CREATE_DATE" VARCHAR2(20), 
	 CONSTRAINT "PK_T_ARTICLE_KEYWORD" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ARTICLE_SOURCE" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"URL" VARCHAR2(255), 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	 CONSTRAINT "PK_T_ARTICLE_SOURCE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ATTACHFILE" 
   (	"URL" VARCHAR2(255), 
	"CONTENT" BLOB, 
	"CREATE_BY" VARCHAR2(10), 
	"CREATE_DATE" VARCHAR2(20), 
	"SITENO" VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
CREATE TABLE "JHCMS"."T_B_BRANCH" 
   (	"BRANCHID" NUMBER(10,0) NOT NULL ENABLE, 
	"BRANCHNO" VARCHAR2(10) NOT NULL ENABLE, 
	"BRANCHNAME" VARCHAR2(256) NOT NULL ENABLE, 
	"REGION" VARCHAR2(40), 
	"CITY" VARCHAR2(128), 
	"ADDRESS" VARCHAR2(256), 
	"ENTRUSTPHONE" VARCHAR2(50), 
	"SERVICEPHONE" VARCHAR2(50), 
	"EMAIL" VARCHAR2(50), 
	"ORDERNUM" NUMBER(10,0), 
	"PHOTO" VARCHAR2(255), 
	"INTRO" CLOB, 
	"LAT" VARCHAR2(64), 
	"LNT" VARCHAR2(64), 
	"ZOOM" NUMBER(10,0), 
	"MAXZOOM" NUMBER(10,0), 
	"CREATEDBY" VARCHAR2(20), 
	"CREATEDTIME" DATE, 
	"MODIFIEDBY" VARCHAR2(20), 
	"MODIFIEDTIME" DATE, 
	"POSTCODE" VARCHAR2(20), 
	"BRANCHINFO" VARCHAR2(4000), 
	"TRAINFO" VARCHAR2(4000), 
	"HANDLERS" CLOB, 
	"SHA_SHB" VARCHAR2(30), 
	"SZA_SZB" VARCHAR2(30), 
	"CHARACTER" CLOB, 
	"BANK" VARCHAR2(4000), 
	"BREED" VARCHAR2(4000), 
	"SITENO" VARCHAR2(50), 
	"BLOG" VARCHAR2(300), 
	 CONSTRAINT "PK_T_B_BRANCH" PRIMARY KEY ("BRANCHID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" 
 LOB ("INTRO") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("HANDLERS") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("CHARACTER") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
CREATE TABLE "JHCMS"."T_B_BRANCH_INFOTYPE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(30), 
	"CREATE_DATE" VARCHAR2(20), 
	"CREATE_NAME" VARCHAR2(20), 
	"SITENO" VARCHAR2(20), 
	 CONSTRAINT "PK_T_B_BRANCH_INFOTYPE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_B_CLIENT_GROUP" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	 CONSTRAINT "PK_T_B_CLIENT_GROUP" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_CATALOG_SEO" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CATALOG_ID" NUMBER(10,0), 
	"TITLE" VARCHAR2(255), 
	"KEYWORDS" VARCHAR2(255), 
	"DESCRIPTION" VARCHAR2(500), 
	"CREATE_BY" VARCHAR2(30), 
	"CREATE_DATE" VARCHAR2(30), 
	"MODIFY_BY" VARCHAR2(30), 
	"MODIFY_DATE" VARCHAR2(30), 
	"SITENO" VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_DEPARTMENT" 
   (	"DEPT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(255), 
	"ORDERLINE" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(10,0), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	 CONSTRAINT "PK_T_DEPARTMENT" PRIMARY KEY ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_DEPT_USER" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DEPT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50), 
	 CONSTRAINT "PK_T_DEPT_USER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ENUM_TYPE" 
   (	"ENUM_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"ENUM_VALUE" VARCHAR2(50) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ENUM_VALUE" 
   (	"ENUM_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"ITEM_VALUE" VARCHAR2(50) NOT NULL ENABLE, 
	"IS_SYSTEM" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDERLINE" NUMBER(10,0) NOT NULL ENABLE, 
	"ITEM_CODE" VARCHAR2(50), 
	"SITENO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_GROUP" 
   (	"GROUP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	 CONSTRAINT "PK_T_GROUP" PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_GROUP_USER" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"GROUP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50), 
	 CONSTRAINT "PK_T_GROUP_USER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_LOG" 
   (	"LOG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"OPERATE" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(800), 
	"IP" VARCHAR2(16), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"BRANCHNO" VARCHAR2(20), 
	"CATALOG_ID" NUMBER(10,0), 
	 CONSTRAINT "PK_T_LOG" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_MANAGE_CATALOG" 
   (	"CATALOG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"CATALOG_NO" VARCHAR2(255) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"ORDERLINE" NUMBER(10,0), 
	"LAYER" NUMBER(10,0), 
	"ROUTE" VARCHAR2(2000), 
	"STATE" NUMBER(10,0) DEFAULT 1, 
	"IS_ROOT" NUMBER(10,0), 
	"IS_SYSTEM" NUMBER(10,0), 
	"LINK_URL" VARCHAR2(255), 
	"SMALL_IMAGE" VARCHAR2(255), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	"CHILDRENNUM" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	 CONSTRAINT "PK_T_MANAGE_CATALOG" PRIMARY KEY ("CATALOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_PUBLISH_ATTACH" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CATALOG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ATTACH_CATALOG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_PUBLISH_LOG" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"QUEUE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	 CONSTRAINT "PK_T_PUBLISH_LOG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_PUBLISH_PLAN" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CATALOG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TYPE" NUMBER(10,0) NOT NULL ENABLE, 
	"TIME" VARCHAR2(30) NOT NULL ENABLE, 
	"PUBLISHTIME" VARCHAR2(30), 
	"RECURSION" NUMBER(10,0), 
	"STATE" NUMBER(10,0) DEFAULT 0, 
	"MACHINE_ID" VARCHAR2(50), 
	 CONSTRAINT "PK_T_PUBLISH_PLAN" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_PUBLISH_QUEUE" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CMD_STR" VARCHAR2(255), 
	"SHOW_INFO" VARCHAR2(255), 
	"STATE" NUMBER(10,0), 
	"SITENO" VARCHAR2(50), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MACHINE_ID" VARCHAR2(50), 
	 CONSTRAINT "PK_T_PUBLISH_QUEUE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ROLE" 
   (	"ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLENO" VARCHAR2(50) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"IS_SYSTEM" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(255), 
	 CONSTRAINT "PK_T_ROLE" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ROLE_CATALOG_RIGHT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TYPE" NUMBER(10,0), 
	"CATALOG_ID_LIST" CLOB, 
	"SITENO" VARCHAR2(50), 
	 CONSTRAINT "PK_T_ROLE_CATALOG_RIGHT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" 
 LOB ("CATALOG_ID_LIST") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
CREATE TABLE "JHCMS"."T_ROLE_RIGHT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CATALOG_NO_LIST" CLOB, 
	"SITENO" VARCHAR2(50), 
	 CONSTRAINT "PK_T_ROLE_RIGHT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" 
 LOB ("CATALOG_NO_LIST") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
CREATE TABLE "JHCMS"."T_ROLE_SITE_RIGHT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITE_NO_LIST" VARCHAR2(400), 
	"SITENO" VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ROLE_USER" 
   (	"ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_SEQUENCE" 
   (	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"CURRENT_VALUE" VARCHAR2(20) NOT NULL ENABLE, 
	"STEP" VARCHAR2(20) NOT NULL ENABLE, 
	"ROLL_BACK" VARCHAR2(20) NOT NULL ENABLE, 
	"START_VALUE" VARCHAR2(20) NOT NULL ENABLE, 
	"MAX_VALUE" VARCHAR2(20) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50), 
	 CONSTRAINT "PK_T_SEQUENCE" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_SITE" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"IS_MAIN" NUMBER(10,0) NOT NULL ENABLE, 
	"PUBLISH_PATH" VARCHAR2(255), 
	"DESCRIPTION" VARCHAR2(200), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	 CONSTRAINT "PK_T_SITE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_SYS_CONFIG" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"CAPTION" VARCHAR2(255) NOT NULL ENABLE, 
	"CUR_VALUE" VARCHAR2(255), 
	"DESCRIPTION" VARCHAR2(500), 
	"IS_SYSTEM" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50), 
	 CONSTRAINT "PK_T_SYS_CONFIG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_TEMPLATE" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"CATALOG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FILEPATH" VARCHAR2(255), 
	"TYPE" NUMBER(10,0) NOT NULL ENABLE, 
	"STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	"CONTENT" CLOB, 
	"ENCODING" VARCHAR2(20), 
	 CONSTRAINT "PK_T_TEMPLATE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
CREATE TABLE "JHCMS"."T_TEMPLATE_VAR" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"ITEM_VALUE" VARCHAR2(4000), 
	"STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(10), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(200), 
	 CONSTRAINT "PK_T_TEMPLATE_VAR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_USER" 
   (	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50), 
	"NAME" VARCHAR2(50), 
	"PASSWORD" VARCHAR2(50), 
	"STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"IS_SYSTEM" NUMBER(10,0) NOT NULL ENABLE, 
	"LOGIN_TIMES" NUMBER(10,0) NOT NULL ENABLE, 
	"LAST_TIME" VARCHAR2(20), 
	"EMAIL" VARCHAR2(50), 
	"PHONE" VARCHAR2(50), 
	"MOBILE" VARCHAR2(50), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(50), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(50), 
	"UID2" VARCHAR2(50), 
	"BRANCHNO" VARCHAR2(10), 
	"SITENAME" VARCHAR2(500), 
	 CONSTRAINT "PK_T_USER" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_CATALOG" 
   (	"CATALOG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"CATALOG_NO" VARCHAR2(30) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(100) NOT NULL ENABLE, 
	"ORDERLINE" NUMBER(10,0), 
	"LAYER" NUMBER(10,0), 
	"ROUTE" VARCHAR2(2000), 
	"STATE" NUMBER(10,0), 
	"NEED_PUBLISH" NUMBER(10,0), 
	"NEED_APPROVE" NUMBER(10,0), 
	"IS_ROOT" NUMBER(10,0), 
	"IS_SYSTEM" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"PAGE_TYPE" NUMBER(10,0), 
	"LINK_URL" VARCHAR2(255), 
	"PUBLISH_PATH" VARCHAR2(255), 
	"FILE_TYPE" VARCHAR2(10), 
	"SMALL_IMAGE" VARCHAR2(255), 
	"LARGE_IMAGE" VARCHAR2(255), 
	"TYPE" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	"USER_RIGHT" NUMBER(10,0) DEFAULT 0, 
	"SPECIAL_URL" VARCHAR2(200), 
	"COLUMN_LEVEL" NUMBER(10,0), 
	"CHILDRENNUM" NUMBER(10,0), 
	"INHERIT_MODE" NUMBER(10,0), 
	"INHERIT_FIELD" NUMBER(10,0) DEFAULT 0, 
	"ATTRIBUTE" NUMBER(10,0) DEFAULT 0, 
	"SOURCE_ID" NUMBER(10,0), 
	"DESCRIPTION" CLOB, 
	 CONSTRAINT "PK_T_CATALOG" PRIMARY KEY ("CATALOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
CREATE TABLE "JHCMS"."T_AD" 
   (	"AD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50), 
	"GROUP_NO" VARCHAR2(50), 
	"TYPE" NUMBER(10,0), 
	"NAME" VARCHAR2(255), 
	"URL" VARCHAR2(255), 
	"PICTURE" VARCHAR2(255), 
	"WIDTH" NUMBER(10,0), 
	"HEIGHT" NUMBER(10,0), 
	"ORDERLINE" NUMBER(10,0), 
	"STATE" NUMBER(10,0), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	"START_TIME" VARCHAR2(30), 
	"END_TIME" VARCHAR2(30), 
	"FILE_TYPE" VARCHAR2(5), 
	"DESCRIPTION" CLOB, 
	"FILE_STATE" VARCHAR2(5), 
	"TEMPLATE" VARCHAR2(5), 
	"TEMPLATE_SIZE" VARCHAR2(5), 
	"TITLE" VARCHAR2(500), 
	 CONSTRAINT "PK_T_AD" PRIMARY KEY ("AD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "JH_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
CREATE TABLE "JHCMS"."T_AD_GROUP" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SITENO" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(20), 
	"MODIFIED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" VARCHAR2(20), 
	"ORDERLINE" NUMBER(10,0), 
	"GROUP_NO" VARCHAR2(50), 
	 CONSTRAINT "PK_AD_GROUP" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JH_DATA" ;
CREATE TABLE "JHCMS"."T_ATTACH_INFO" 
   (	"ATTACH_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"SOURCE" CHAR(1) NOT NULL ENABLE, 
	"SOURCE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SAVE_FILENAME" VARCHAR2(255), 
	"REAL_FILANAME" VARCHAR2(255), 
	"URL" VARCHAR2(500), 
	"CREATE_BY" VARCHAR2(50), 
	"CREATE_DATE" VARCHAR2(30), 
	"DOWN_COUNT" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JH_DATA";
 
