package com.jhcz.cms.model;

public class CatalogEntity
{
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.CATALOG_ID
	 *
	 * @mbggenerated
	 */
	private Long catalogId;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.PARENT_ID
	 *
	 * @mbggenerated
	 */
	private Long parentId;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.NAME
	 *
	 * @mbggenerated
	 */
	private String name;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.CATALOG_NO
	 *
	 * @mbggenerated
	 */
	private String catalogNo;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.SITENO
	 *
	 * @mbggenerated
	 */
	private String siteno;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.ORDERLINE
	 *
	 * @mbggenerated
	 */
	private Long orderline;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.LAYER
	 *
	 * @mbggenerated
	 */
	private Long layer;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.ROUTE
	 *
	 * @mbggenerated
	 */
	private String route;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.STATE
	 *
	 * @mbggenerated
	 */
	private Long state;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.NEED_PUBLISH
	 *
	 * @mbggenerated
	 */
	private Long needPublish;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.NEED_APPROVE
	 *
	 * @mbggenerated
	 */
	private Long needApprove;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.IS_ROOT
	 *
	 * @mbggenerated
	 */
	private Long isRoot;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.IS_SYSTEM
	 *
	 * @mbggenerated
	 */
	private Long isSystem;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.PAGE_TYPE
	 *
	 * @mbggenerated
	 */
	private Long pageType;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.LINK_URL
	 *
	 * @mbggenerated
	 */
	private String linkUrl;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.PUBLISH_PATH
	 *
	 * @mbggenerated
	 */
	private String publishPath;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.FILE_TYPE
	 *
	 * @mbggenerated
	 */
	private String fileType;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.SMALL_IMAGE
	 *
	 * @mbggenerated
	 */
	private String smallImage;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.LARGE_IMAGE
	 *
	 * @mbggenerated
	 */
	private String largeImage;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.TYPE
	 *
	 * @mbggenerated
	 */
	private Long type;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.CREATE_BY
	 *
	 * @mbggenerated
	 */
	private String createBy;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.CREATE_DATE
	 *
	 * @mbggenerated
	 */
	private String createDate;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.MODIFIED_BY
	 *
	 * @mbggenerated
	 */
	private String modifiedBy;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.MODIFIED_DATE
	 *
	 * @mbggenerated
	 */
	private String modifiedDate;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.USER_RIGHT
	 *
	 * @mbggenerated
	 */
	private Long userRight;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.SPECIAL_URL
	 *
	 * @mbggenerated
	 */
	private String specialUrl;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.COLUMN_LEVEL
	 *
	 * @mbggenerated
	 */
	private Long columnLevel;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.CHILDRENNUM
	 *
	 * @mbggenerated
	 */
	private Long childrennum;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.INHERIT_MODE
	 *
	 * @mbggenerated
	 */
	private Long inheritMode;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.INHERIT_FIELD
	 *
	 * @mbggenerated
	 */
	private Long inheritField;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.ATTRIBUTE
	 *
	 * @mbggenerated
	 */
	private Long attribute;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.SOURCE_ID
	 *
	 * @mbggenerated
	 */
	private Long sourceId;
	
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column JHCMS.T_CATALOG.DESCRIPTION
	 *
	 * @mbggenerated
	 */
	private String description;
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.CATALOG_ID
	 *
	 * @return the value of JHCMS.T_CATALOG.CATALOG_ID
	 *
	 * @mbggenerated
	 */
	public Long getCatalogId()
	{
		return catalogId;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.CATALOG_ID
	 *
	 * @param catalogId the value for JHCMS.T_CATALOG.CATALOG_ID
	 *
	 * @mbggenerated
	 */
	public void setCatalogId(Long catalogId)
	{
		this.catalogId = catalogId;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.PARENT_ID
	 *
	 * @return the value of JHCMS.T_CATALOG.PARENT_ID
	 *
	 * @mbggenerated
	 */
	public Long getParentId()
	{
		return parentId;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.PARENT_ID
	 *
	 * @param parentId the value for JHCMS.T_CATALOG.PARENT_ID
	 *
	 * @mbggenerated
	 */
	public void setParentId(Long parentId)
	{
		this.parentId = parentId;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.NAME
	 *
	 * @return the value of JHCMS.T_CATALOG.NAME
	 *
	 * @mbggenerated
	 */
	public String getName()
	{
		return name;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.NAME
	 *
	 * @param name the value for JHCMS.T_CATALOG.NAME
	 *
	 * @mbggenerated
	 */
	public void setName(String name)
	{
		this.name = name == null ? null : name.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.CATALOG_NO
	 *
	 * @return the value of JHCMS.T_CATALOG.CATALOG_NO
	 *
	 * @mbggenerated
	 */
	public String getCatalogNo()
	{
		return catalogNo;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.CATALOG_NO
	 *
	 * @param catalogNo the value for JHCMS.T_CATALOG.CATALOG_NO
	 *
	 * @mbggenerated
	 */
	public void setCatalogNo(String catalogNo)
	{
		this.catalogNo = catalogNo == null ? null : catalogNo.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.SITENO
	 *
	 * @return the value of JHCMS.T_CATALOG.SITENO
	 *
	 * @mbggenerated
	 */
	public String getSiteno()
	{
		return siteno;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.SITENO
	 *
	 * @param siteno the value for JHCMS.T_CATALOG.SITENO
	 *
	 * @mbggenerated
	 */
	public void setSiteno(String siteno)
	{
		this.siteno = siteno == null ? null : siteno.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.ORDERLINE
	 *
	 * @return the value of JHCMS.T_CATALOG.ORDERLINE
	 *
	 * @mbggenerated
	 */
	public Long getOrderline()
	{
		return orderline;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.ORDERLINE
	 *
	 * @param orderline the value for JHCMS.T_CATALOG.ORDERLINE
	 *
	 * @mbggenerated
	 */
	public void setOrderline(Long orderline)
	{
		this.orderline = orderline;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.LAYER
	 *
	 * @return the value of JHCMS.T_CATALOG.LAYER
	 *
	 * @mbggenerated
	 */
	public Long getLayer()
	{
		return layer;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.LAYER
	 *
	 * @param layer the value for JHCMS.T_CATALOG.LAYER
	 *
	 * @mbggenerated
	 */
	public void setLayer(Long layer)
	{
		this.layer = layer;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.ROUTE
	 *
	 * @return the value of JHCMS.T_CATALOG.ROUTE
	 *
	 * @mbggenerated
	 */
	public String getRoute()
	{
		return route;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.ROUTE
	 *
	 * @param route the value for JHCMS.T_CATALOG.ROUTE
	 *
	 * @mbggenerated
	 */
	public void setRoute(String route)
	{
		this.route = route == null ? null : route.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.STATE
	 *
	 * @return the value of JHCMS.T_CATALOG.STATE
	 *
	 * @mbggenerated
	 */
	public Long getState()
	{
		return state;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.STATE
	 *
	 * @param state the value for JHCMS.T_CATALOG.STATE
	 *
	 * @mbggenerated
	 */
	public void setState(Long state)
	{
		this.state = state;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.NEED_PUBLISH
	 *
	 * @return the value of JHCMS.T_CATALOG.NEED_PUBLISH
	 *
	 * @mbggenerated
	 */
	public Long getNeedPublish()
	{
		return needPublish;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.NEED_PUBLISH
	 *
	 * @param needPublish the value for JHCMS.T_CATALOG.NEED_PUBLISH
	 *
	 * @mbggenerated
	 */
	public void setNeedPublish(Long needPublish)
	{
		this.needPublish = needPublish;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.NEED_APPROVE
	 *
	 * @return the value of JHCMS.T_CATALOG.NEED_APPROVE
	 *
	 * @mbggenerated
	 */
	public Long getNeedApprove()
	{
		return needApprove;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.NEED_APPROVE
	 *
	 * @param needApprove the value for JHCMS.T_CATALOG.NEED_APPROVE
	 *
	 * @mbggenerated
	 */
	public void setNeedApprove(Long needApprove)
	{
		this.needApprove = needApprove;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.IS_ROOT
	 *
	 * @return the value of JHCMS.T_CATALOG.IS_ROOT
	 *
	 * @mbggenerated
	 */
	public Long getIsRoot()
	{
		return isRoot;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.IS_ROOT
	 *
	 * @param isRoot the value for JHCMS.T_CATALOG.IS_ROOT
	 *
	 * @mbggenerated
	 */
	public void setIsRoot(Long isRoot)
	{
		this.isRoot = isRoot;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.IS_SYSTEM
	 *
	 * @return the value of JHCMS.T_CATALOG.IS_SYSTEM
	 *
	 * @mbggenerated
	 */
	public Long getIsSystem()
	{
		return isSystem;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.IS_SYSTEM
	 *
	 * @param isSystem the value for JHCMS.T_CATALOG.IS_SYSTEM
	 *
	 * @mbggenerated
	 */
	public void setIsSystem(Long isSystem)
	{
		this.isSystem = isSystem;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.PAGE_TYPE
	 *
	 * @return the value of JHCMS.T_CATALOG.PAGE_TYPE
	 *
	 * @mbggenerated
	 */
	public Long getPageType()
	{
		return pageType;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.PAGE_TYPE
	 *
	 * @param pageType the value for JHCMS.T_CATALOG.PAGE_TYPE
	 *
	 * @mbggenerated
	 */
	public void setPageType(Long pageType)
	{
		this.pageType = pageType;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.LINK_URL
	 *
	 * @return the value of JHCMS.T_CATALOG.LINK_URL
	 *
	 * @mbggenerated
	 */
	public String getLinkUrl()
	{
		return linkUrl;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.LINK_URL
	 *
	 * @param linkUrl the value for JHCMS.T_CATALOG.LINK_URL
	 *
	 * @mbggenerated
	 */
	public void setLinkUrl(String linkUrl)
	{
		this.linkUrl = linkUrl == null ? null : linkUrl.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.PUBLISH_PATH
	 *
	 * @return the value of JHCMS.T_CATALOG.PUBLISH_PATH
	 *
	 * @mbggenerated
	 */
	public String getPublishPath()
	{
		return publishPath;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.PUBLISH_PATH
	 *
	 * @param publishPath the value for JHCMS.T_CATALOG.PUBLISH_PATH
	 *
	 * @mbggenerated
	 */
	public void setPublishPath(String publishPath)
	{
		this.publishPath = publishPath == null ? null : publishPath.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.FILE_TYPE
	 *
	 * @return the value of JHCMS.T_CATALOG.FILE_TYPE
	 *
	 * @mbggenerated
	 */
	public String getFileType()
	{
		return fileType;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.FILE_TYPE
	 *
	 * @param fileType the value for JHCMS.T_CATALOG.FILE_TYPE
	 *
	 * @mbggenerated
	 */
	public void setFileType(String fileType)
	{
		this.fileType = fileType == null ? null : fileType.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.SMALL_IMAGE
	 *
	 * @return the value of JHCMS.T_CATALOG.SMALL_IMAGE
	 *
	 * @mbggenerated
	 */
	public String getSmallImage()
	{
		return smallImage;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.SMALL_IMAGE
	 *
	 * @param smallImage the value for JHCMS.T_CATALOG.SMALL_IMAGE
	 *
	 * @mbggenerated
	 */
	public void setSmallImage(String smallImage)
	{
		this.smallImage = smallImage == null ? null : smallImage.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.LARGE_IMAGE
	 *
	 * @return the value of JHCMS.T_CATALOG.LARGE_IMAGE
	 *
	 * @mbggenerated
	 */
	public String getLargeImage()
	{
		return largeImage;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.LARGE_IMAGE
	 *
	 * @param largeImage the value for JHCMS.T_CATALOG.LARGE_IMAGE
	 *
	 * @mbggenerated
	 */
	public void setLargeImage(String largeImage)
	{
		this.largeImage = largeImage == null ? null : largeImage.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.TYPE
	 *
	 * @return the value of JHCMS.T_CATALOG.TYPE
	 *
	 * @mbggenerated
	 */
	public Long getType()
	{
		return type;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.TYPE
	 *
	 * @param type the value for JHCMS.T_CATALOG.TYPE
	 *
	 * @mbggenerated
	 */
	public void setType(Long type)
	{
		this.type = type;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.CREATE_BY
	 *
	 * @return the value of JHCMS.T_CATALOG.CREATE_BY
	 *
	 * @mbggenerated
	 */
	public String getCreateBy()
	{
		return createBy;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.CREATE_BY
	 *
	 * @param createBy the value for JHCMS.T_CATALOG.CREATE_BY
	 *
	 * @mbggenerated
	 */
	public void setCreateBy(String createBy)
	{
		this.createBy = createBy == null ? null : createBy.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.CREATE_DATE
	 *
	 * @return the value of JHCMS.T_CATALOG.CREATE_DATE
	 *
	 * @mbggenerated
	 */
	public String getCreateDate()
	{
		return createDate;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.CREATE_DATE
	 *
	 * @param createDate the value for JHCMS.T_CATALOG.CREATE_DATE
	 *
	 * @mbggenerated
	 */
	public void setCreateDate(String createDate)
	{
		this.createDate = createDate == null ? null : createDate.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.MODIFIED_BY
	 *
	 * @return the value of JHCMS.T_CATALOG.MODIFIED_BY
	 *
	 * @mbggenerated
	 */
	public String getModifiedBy()
	{
		return modifiedBy;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.MODIFIED_BY
	 *
	 * @param modifiedBy the value for JHCMS.T_CATALOG.MODIFIED_BY
	 *
	 * @mbggenerated
	 */
	public void setModifiedBy(String modifiedBy)
	{
		this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.MODIFIED_DATE
	 *
	 * @return the value of JHCMS.T_CATALOG.MODIFIED_DATE
	 *
	 * @mbggenerated
	 */
	public String getModifiedDate()
	{
		return modifiedDate;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.MODIFIED_DATE
	 *
	 * @param modifiedDate the value for JHCMS.T_CATALOG.MODIFIED_DATE
	 *
	 * @mbggenerated
	 */
	public void setModifiedDate(String modifiedDate)
	{
		this.modifiedDate = modifiedDate == null ? null : modifiedDate.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.USER_RIGHT
	 *
	 * @return the value of JHCMS.T_CATALOG.USER_RIGHT
	 *
	 * @mbggenerated
	 */
	public Long getUserRight()
	{
		return userRight;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.USER_RIGHT
	 *
	 * @param userRight the value for JHCMS.T_CATALOG.USER_RIGHT
	 *
	 * @mbggenerated
	 */
	public void setUserRight(Long userRight)
	{
		this.userRight = userRight;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.SPECIAL_URL
	 *
	 * @return the value of JHCMS.T_CATALOG.SPECIAL_URL
	 *
	 * @mbggenerated
	 */
	public String getSpecialUrl()
	{
		return specialUrl;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.SPECIAL_URL
	 *
	 * @param specialUrl the value for JHCMS.T_CATALOG.SPECIAL_URL
	 *
	 * @mbggenerated
	 */
	public void setSpecialUrl(String specialUrl)
	{
		this.specialUrl = specialUrl == null ? null : specialUrl.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.COLUMN_LEVEL
	 *
	 * @return the value of JHCMS.T_CATALOG.COLUMN_LEVEL
	 *
	 * @mbggenerated
	 */
	public Long getColumnLevel()
	{
		return columnLevel;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.COLUMN_LEVEL
	 *
	 * @param columnLevel the value for JHCMS.T_CATALOG.COLUMN_LEVEL
	 *
	 * @mbggenerated
	 */
	public void setColumnLevel(Long columnLevel)
	{
		this.columnLevel = columnLevel;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.CHILDRENNUM
	 *
	 * @return the value of JHCMS.T_CATALOG.CHILDRENNUM
	 *
	 * @mbggenerated
	 */
	public Long getChildrennum()
	{
		return childrennum;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.CHILDRENNUM
	 *
	 * @param childrennum the value for JHCMS.T_CATALOG.CHILDRENNUM
	 *
	 * @mbggenerated
	 */
	public void setChildrennum(Long childrennum)
	{
		this.childrennum = childrennum;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.INHERIT_MODE
	 *
	 * @return the value of JHCMS.T_CATALOG.INHERIT_MODE
	 *
	 * @mbggenerated
	 */
	public Long getInheritMode()
	{
		return inheritMode;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.INHERIT_MODE
	 *
	 * @param inheritMode the value for JHCMS.T_CATALOG.INHERIT_MODE
	 *
	 * @mbggenerated
	 */
	public void setInheritMode(Long inheritMode)
	{
		this.inheritMode = inheritMode;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.INHERIT_FIELD
	 *
	 * @return the value of JHCMS.T_CATALOG.INHERIT_FIELD
	 *
	 * @mbggenerated
	 */
	public Long getInheritField()
	{
		return inheritField;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.INHERIT_FIELD
	 *
	 * @param inheritField the value for JHCMS.T_CATALOG.INHERIT_FIELD
	 *
	 * @mbggenerated
	 */
	public void setInheritField(Long inheritField)
	{
		this.inheritField = inheritField;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.ATTRIBUTE
	 *
	 * @return the value of JHCMS.T_CATALOG.ATTRIBUTE
	 *
	 * @mbggenerated
	 */
	public Long getAttribute()
	{
		return attribute;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.ATTRIBUTE
	 *
	 * @param attribute the value for JHCMS.T_CATALOG.ATTRIBUTE
	 *
	 * @mbggenerated
	 */
	public void setAttribute(Long attribute)
	{
		this.attribute = attribute;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.SOURCE_ID
	 *
	 * @return the value of JHCMS.T_CATALOG.SOURCE_ID
	 *
	 * @mbggenerated
	 */
	public Long getSourceId()
	{
		return sourceId;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.SOURCE_ID
	 *
	 * @param sourceId the value for JHCMS.T_CATALOG.SOURCE_ID
	 *
	 * @mbggenerated
	 */
	public void setSourceId(Long sourceId)
	{
		this.sourceId = sourceId;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column JHCMS.T_CATALOG.DESCRIPTION
	 *
	 * @return the value of JHCMS.T_CATALOG.DESCRIPTION
	 *
	 * @mbggenerated
	 */
	public String getDescription()
	{
		return description;
	}
	
	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column JHCMS.T_CATALOG.DESCRIPTION
	 *
	 * @param description the value for JHCMS.T_CATALOG.DESCRIPTION
	 *
	 * @mbggenerated
	 */
	public void setDescription(String description)
	{
		this.description = description == null ? null : description.trim();
	}
}