/*
 * JSP generated by Resin Professional 3.1.9 (built Mon, 13 Apr 2009 11:15:04 PDT)
 */

package _jsp._web_22dinf._views._article;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _ajaxarticlelist__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jsp_ChooseTag_0 = null;
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jsp_WhenTag_1 = null;
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jsp_ForEachTag_2 = null;
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jsp_ChooseTag_3 = null;
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jsp_WhenTag_4 = null;
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jsp_OtherwiseTag_5 = null;
    org.apache.taglibs.standard.tag.rt.core.IfTag _jsp_IfTag_6 = null;
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jsp_OtherwiseTag_7 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      request.setAttribute("contextPath", request.getContextPath());
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_ChooseTag_0 == null) {
        _jsp_ChooseTag_0 = new org.apache.taglibs.standard.tag.common.core.ChooseTag();
        _jsp_ChooseTag_0.setPageContext(pageContext);
        _jsp_ChooseTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_ChooseTag_0.doStartTag();
      out.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_WhenTag_1 == null) {
        _jsp_WhenTag_1 = new org.apache.taglibs.standard.tag.rt.core.WhenTag();
        _jsp_WhenTag_1.setPageContext(pageContext);
        _jsp_WhenTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ChooseTag_0);
      }

      _jsp_WhenTag_1.setTest(_caucho_expr_0.evalBoolean(_jsp_env));
      int _jspEval5 = _jsp_WhenTag_1.doStartTag();
      if (_jspEval5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(_jsp_string1, 0, _jsp_string1.length);
        if (_jsp_ForEachTag_2 == null) {
          _jsp_ForEachTag_2 = new org.apache.taglibs.standard.tag.rt.core.ForEachTag();
          _jsp_ForEachTag_2.setPageContext(pageContext);
          _jsp_ForEachTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_WhenTag_1);
          _jsp_ForEachTag_2.setVar("item");
          _jsp_ForEachTag_2.setVarStatus("status");
        }

        _jsp_ForEachTag_2.setItems(_caucho_expr_1.evalObject(_jsp_env));
        javax.servlet.jsp.JspWriter _jsp_writer7 = out;
        try {
          int _jspEval8 = _jsp_ForEachTag_2.doStartTag();
          if (_jspEval8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write(_jsp_string2, 0, _jsp_string2.length);
              _caucho_expr_2.print(out, _jsp_env, false);
              out.write(_jsp_string3, 0, _jsp_string3.length);
              _caucho_expr_3.print(out, _jsp_env, false);
              out.write(_jsp_string4, 0, _jsp_string4.length);
              _caucho_expr_4.print(out, _jsp_env, false);
              out.write(_jsp_string5, 0, _jsp_string5.length);
              _caucho_expr_5.print(out, _jsp_env, false);
              out.write(_jsp_string6, 0, _jsp_string6.length);
              if (_jsp_ChooseTag_3 == null) {
                _jsp_ChooseTag_3 = new org.apache.taglibs.standard.tag.common.core.ChooseTag();
                _jsp_ChooseTag_3.setPageContext(pageContext);
                _jsp_ChooseTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ForEachTag_2);
              }

              _jsp_ChooseTag_3.doStartTag();
              out.write(_jsp_string7, 0, _jsp_string7.length);
              if (_jsp_WhenTag_4 == null) {
                _jsp_WhenTag_4 = new org.apache.taglibs.standard.tag.rt.core.WhenTag();
                _jsp_WhenTag_4.setPageContext(pageContext);
                _jsp_WhenTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ChooseTag_3);
              }

              _jsp_WhenTag_4.setTest(_caucho_expr_6.evalBoolean(_jsp_env));
              int _jspEval14 = _jsp_WhenTag_4.doStartTag();
              if (_jspEval14 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                out.write(_jsp_string8, 0, _jsp_string8.length);
                _caucho_expr_7.print(out, _jsp_env, false);
                out.write(_jsp_string9, 0, _jsp_string9.length);
              }
              out.write(_jsp_string7, 0, _jsp_string7.length);
              if (_jsp_OtherwiseTag_5 == null) {
                _jsp_OtherwiseTag_5 = new org.apache.taglibs.standard.tag.common.core.OtherwiseTag();
                _jsp_OtherwiseTag_5.setPageContext(pageContext);
                _jsp_OtherwiseTag_5.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ChooseTag_3);
              }

              int _jspEval18 = _jsp_OtherwiseTag_5.doStartTag();
              if (_jspEval18 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                out.write(_jsp_string8, 0, _jsp_string8.length);
                _caucho_expr_8.print(out, _jsp_env, false);
                out.write(_jsp_string7, 0, _jsp_string7.length);
              }
              out.write(_jsp_string10, 0, _jsp_string10.length);
              _caucho_expr_9.print(out, _jsp_env, false);
              out.write(_jsp_string11, 0, _jsp_string11.length);
              if (_jsp_IfTag_6 == null) {
                _jsp_IfTag_6 = new org.apache.taglibs.standard.tag.rt.core.IfTag();
                _jsp_IfTag_6.setPageContext(pageContext);
                _jsp_IfTag_6.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ForEachTag_2);
              }

              _jsp_IfTag_6.setTest(_caucho_expr_10.evalBoolean(_jsp_env));
              int _jspEval23 = _jsp_IfTag_6.doStartTag();
              if (_jspEval23 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                out.write(_jsp_string12, 0, _jsp_string12.length);
              }
              out.write(_jsp_string1, 0, _jsp_string1.length);
            } while (_jsp_ForEachTag_2.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
          }
        } catch (Throwable _jsp_exn_26) {
          pageContext.setWriter(_jsp_writer7);
          out = _jsp_writer7;
          _jsp_ForEachTag_2.doCatch(_jsp_exn_26);
        } finally {
          _jsp_ForEachTag_2.doFinally();
        }
        out.write(_jsp_string1, 0, _jsp_string1.length);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_OtherwiseTag_7 == null) {
        _jsp_OtherwiseTag_7 = new org.apache.taglibs.standard.tag.common.core.OtherwiseTag();
        _jsp_OtherwiseTag_7.setPageContext(pageContext);
        _jsp_OtherwiseTag_7.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ChooseTag_0);
      }

      int _jspEval30 = _jsp_OtherwiseTag_7.doStartTag();
      if (_jspEval30 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(_jsp_string13, 0, _jsp_string13.length);
      }
      out.write(_jsp_string14, 0, _jsp_string14.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_ChooseTag_0 != null)
        _jsp_ChooseTag_0.release();
      if (_jsp_WhenTag_1 != null)
        _jsp_WhenTag_1.release();
      if (_jsp_ForEachTag_2 != null)
        _jsp_ForEachTag_2.release();
      if (_jsp_ChooseTag_3 != null)
        _jsp_ChooseTag_3.release();
      if (_jsp_WhenTag_4 != null)
        _jsp_WhenTag_4.release();
      if (_jsp_OtherwiseTag_5 != null)
        _jsp_OtherwiseTag_5.release();
      if (_jsp_IfTag_6 != null)
        _jsp_IfTag_6.release();
      if (_jsp_OtherwiseTag_7 != null)
        _jsp_OtherwiseTag_7.release();
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7224303694680427414L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "/tags/jstl-core");
    manager.addTaglibFunctions(_jsp_functionMap, "fmt", "/tags/jstl-format");
    manager.addTaglibFunctions(_jsp_functionMap, "fn", "/tags/jstl-function");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${not empty page.data}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${page.data}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${item.url }");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${status.index + 1}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${item.title }");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${fn:substring(item.publish_date,0,10) }");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${fn:length(item.brief) > 60}");
    _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${fn:substring(item.brief,0,60) }");
    _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${item.brief }");
    _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${item.url}");
    _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${status.index + 1 < fn:length(page.data) }");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/views/article/ajaxArticleList.jsp"), 199727715244473025L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/views/include/taglibs.jsp"), 4094030800207755393L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tlds/c.tld"), -8665009061218735675L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.taglibs.standard.tag.rt.core.WhenTag.class, -849494588761764570L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class, 8895294544743214897L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.taglibs.standard.tag.common.core.ChooseTag.class, -3913156568694213888L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.taglibs.standard.tag.rt.core.IfTag.class, 730507363017296415L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class, 2280997101442528701L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.taglibs.standard.tei.ForEachTEI.class, -6853184308858869335L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;

  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  private final static char []_jsp_string9;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string13;
  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string8;
  private final static char []_jsp_string10;
  private final static char []_jsp_string12;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string11;
  private final static char []_jsp_string14;
  static {
    _jsp_string4 = ".jpg\" alt=\"\"></a>\r\n				<div class=\"news_title\">".toCharArray();
    _jsp_string1 = "\r\n	".toCharArray();
    _jsp_string9 = "...\r\n					".toCharArray();
    _jsp_string7 = "\r\n					".toCharArray();
    _jsp_string2 = "\r\n		<li class=\"news_list_table\">\r\n			<div class=\"news_list_table_jpg\">\r\n				<a href=\"".toCharArray();
    _jsp_string13 = "\r\n			\u6682\u65e0\u6570\u636e!\r\n	".toCharArray();
    _jsp_string6 = "</div>\r\n				<div class=\"news_profile\">\r\n				".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string8 = "\r\n						".toCharArray();
    _jsp_string10 = "\r\n				\r\n				</div>\r\n				<a class=\"news_selectDetail\" href=\"".toCharArray();
    _jsp_string12 = "\r\n		<div class=\"news_borderline\"></div>\r\n		".toCharArray();
    _jsp_string3 = "\" target=\"_blank\"><img src=\"/component/app/images/news/picture".toCharArray();
    _jsp_string5 = "</div>\r\n				<div class=\"news_date\">".toCharArray();
    _jsp_string11 = "\" target=\"_blank\">\u67e5\u770b\u8be6\u60c5<div class=\"news_iconImg\"></div></a>\r\n			</div>\r\n		</li>\r\n		".toCharArray();
    _jsp_string14 = "\r\n\r\n".toCharArray();
  }
}
